config/routes.rb
Rails.application.routes.draw do
  resources :vouchers
  resources :restaurants, only: [:show, :index, :new, :create, :edit, :update, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :vouchers
end

app/models/voucher.rb
class Voucher < ApplicationRecord
  # belongs_to :restaurant
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  # GET /restaurants
  # GET /restaurants.json
  def index
    @restaurants = Restaurant.all
  end

  # GET /restaurants/1
  # GET /restaurants/1.json
  def show
  end

  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
  end

  # GET /restaurants/1/edit
  def edit
  end

  # POST /restaurants
  # POST /restaurants.json
  def create
    @restaurant = Restaurant.new(restaurant_params)

    respond_to do |format|
      if @restaurant.save
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully created.' }
        format.json { render :show, status: :created, location: @restaurant }
      else
        format.html { render :new }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /restaurants/1
  # PATCH/PUT /restaurants/1.json
  def update
    respond_to do |format|
      if @restaurant.update(restaurant_params)
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully updated.' }
        format.json { render :show, status: :ok, location: @restaurant }
      else
        format.html { render :edit }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurants/1
  # DELETE /restaurants/1.json
  def destroy
    @restaurant.destroy
    respond_to do |format|
      format.html { redirect_to restaurants_url, notice: 'Restaurant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def restaurant_params
      params.require(:restaurant).permit(:latitude, :longitude, :name, :city, :neighbourhood, :address)
    end
end

app/controllers/vouchers_controller.rb
class VouchersController < ApplicationController
  before_action :set_voucher, only: [:show, :edit, :update, :destroy]

  # GET /vouchers
  # GET /vouchers.json
  def index
    @vouchers = Voucher.all
  end

  # GET /vouchers/1
  # GET /vouchers/1.json
  def show
  end

  # GET /vouchers/new
  def new
    @voucher = Voucher.new
  end

  # GET /vouchers/1/edit
  def edit
  end

  # POST /vouchers
  # POST /vouchers.json
  def create
    restaurant = Restaurant.find_by(name: params["voucher"][:restaurant])
    restaurant = create_restaurant(params["voucher"][:restaurant]) if restaurant.nil?

    @voucher = Voucher.new(voucher_params)
    @voucher[:restaurant] = restaurant
    respond_to do |format|
      if @voucher.save
        format.html { redirect_to @voucher, notice: 'Voucher was successfully created.' }
        format.json { render :show, status: :created, location: @voucher }
      else
        format.html { render :new }
        format.json { render json: @voucher.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vouchers/1
  # PATCH/PUT /vouchers/1.json
  def update
    respond_to do |format|
      if @voucher.update(voucher_params)
        format.html { redirect_to @voucher, notice: 'Voucher was successfully updated.' }
        format.json { render :show, status: :ok, location: @voucher }
      else
        format.html { render :edit }
        format.json { render json: @voucher.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vouchers/1
  # DELETE /vouchers/1.json
  def destroy
    @voucher.destroy
    respond_to do |format|
      format.html { redirect_to vouchers_url, notice: 'Voucher was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def create_restaurant(params)
    restaurant = Restaurant.new(name: params)
    restaurant.save
    return restaurant
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_voucher
      @voucher = Voucher.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def voucher_params
      params.require(:voucher).permit(:cost, :notes)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurant_helper.rb
module RestaurantHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/vouchers_helper.rb
module VouchersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Covoucher</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurant/create.html.erb
<h1>Restaurant#create</h1>
<p>Find me in app/views/restaurant/create.html.erb</p>

app/views/restaurant/destroy.html.erb
<h1>Restaurant#destroy</h1>
<p>Find me in app/views/restaurant/destroy.html.erb</p>

app/views/restaurant/edit.html.erb
<h1>Restaurant#edit</h1>
<p>Find me in app/views/restaurant/edit.html.erb</p>

app/views/restaurant/index.html.erb
<h1>Restaurant#index</h1>
<p>Find me in app/views/restaurant/index.html.erb</p>

<% @restaurants.each do |restaurant| %>
  <h2><%= restaurant.name %></h2>
  <p><%= restaurant.address %></p>
<% end %>

app/views/restaurant/new.html.erb
<h1>Restaurant#new</h1>
<p>Find me in app/views/restaurant/new.html.erb</p>

app/views/restaurant/show.html.erb
<h1>Restaurant#show</h1>
<p>Find me in app/views/restaurant/show.html.erb</p>

<h2><%= @restaurant.name %></h2>
<p><%= @restaurant.address %></p>

app/views/restaurant/update.html.erb
<h1>Restaurant#update</h1>
<p>Find me in app/views/restaurant/update.html.erb</p>

app/views/restaurants/_form.html.erb
<%= form_with(model: restaurant, local: true) do |form| %>
  <% if restaurant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h2>

      <ul>
      <% restaurant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :latitude %>
    <%= form.text_field :latitude %>
  </div>

  <div class="field">
    <%= form.label :longitude %>
    <%= form.text_field :longitude %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city %>
  </div>

  <div class="field">
    <%= form.label :neighbourhood %>
    <%= form.text_field :neighbourhood %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Editing Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

<%= link_to 'Show', @restaurant %> |
<%= link_to 'Back', restaurants_path %>

app/views/restaurants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Restaurants</h1>

<table>
  <thead>
    <tr>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Name</th>
      <th>City</th>
      <th>Neighbourhood</th>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @restaurants.each do |restaurant| %>
      <tr>
        <td><%= restaurant.latitude %></td>
        <td><%= restaurant.longitude %></td>
        <td><%= restaurant.name %></td>
        <td><%= restaurant.city %></td>
        <td><%= restaurant.neighbourhood %></td>
        <td><%= restaurant.address %></td>
        <td><%= link_to 'Show', restaurant %></td>
        <td><%= link_to 'Edit', edit_restaurant_path(restaurant) %></td>
        <td><%= link_to 'Destroy', restaurant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Restaurant', new_restaurant_path %>

app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

<%= link_to 'Back', restaurants_path %>

app/views/restaurants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Latitude:</strong>
  <%= @restaurant.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @restaurant.longitude %>
</p>

<p>
  <strong>Name:</strong>
  <%= @restaurant.name %>
</p>

<p>
  <strong>City:</strong>
  <%= @restaurant.city %>
</p>

<p>
  <strong>Neighbourhood:</strong>
  <%= @restaurant.neighbourhood %>
</p>

<p>
  <strong>Address:</strong>
  <%= @restaurant.address %>
</p>

<%= link_to 'Edit', edit_restaurant_path(@restaurant) %> |
<%= link_to 'Back', restaurants_path %>

app/views/vouchers/_form.html.erb
<%= form_with(model: voucher, local: true) do |form| %>
  <% if voucher.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(voucher.errors.count, "error") %> prohibited this voucher from being saved:</h2>

      <ul>
      <% voucher.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :restaurant %>
    <%= form.text_field :restaurant %>
  </div>

  <div class="field">
    <%= form.label :cost %>
    <%= form.number_field :cost %>
  </div>

  <div class="field">
    <%= form.label :notes %>
    <%= form.text_field :notes %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/vouchers/edit.html.erb
<h1>Editing Voucher</h1>

<%= render 'form', voucher: @voucher %>

<%= link_to 'Show', @voucher %> |
<%= link_to 'Back', vouchers_path %>

app/views/vouchers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Vouchers</h1>

<table>
  <thead>
    <tr>
      <th>Cost</th>
      <th>Notes</th>
      <th>Restaurant</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vouchers.each do |voucher| %>
      <tr>
        <td><%= voucher.cost %></td>
        <td><%= voucher.notes %></td>
        <td><%= Restaurant.find(voucher[:restaurant]).name %></td>
        <td><%= link_to 'Show', voucher %></td>
        <td><%= link_to 'Edit', edit_voucher_path(voucher) %></td>
        <td><%= link_to 'Destroy', voucher, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Voucher', new_voucher_path %>

app/views/vouchers/new.html.erb
<h1>New Voucher</h1>

<%= render 'form', voucher: @voucher %>

<%= link_to 'Back', vouchers_path %>

app/views/vouchers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cost:</strong>
  <%= @voucher.cost %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @voucher.notes %>
</p>

<%= link_to 'Edit', edit_voucher_path(@voucher) %> |
<%= link_to 'Back', vouchers_path %>